=== ilialeonov/Epam_training/task4/Candies/dataXML/Candies.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.by/candies"
        xmlns:tns="http://www.epam.by/candies"
           elementFormDefault="qualified">
    
    <element name="candies">
        <complexType>
            <sequence>
                <element name = "candy" 
                         type = "tns:Candy"
                         minOccurs = "16"
                         maxOccurs = "21"/>
            </sequence>
        </complexType>
    </element>
    
    <complexType name = "Candy">
        <sequence>
            <element name = "name">
                <simpleType>
                    <restriction base = "ID">
                        <pattern value="[A-Z](\w+){3,21}"/>
                    </restriction>
                </simpleType>
            </element>            
            <element name = "energy" type = "tns:Energy"/>
            <element name = "type" type = "tns:Type"/>
            <element name = "ingridients" type = "tns:Ingridients"/>
            <element name = "value" type = "tns:Value"/>
            <element name = "production">
                <simpleType>
                    <restriction base = "string">
                        <pattern value="[A-Z](\w+){3,21}"/>
                    </restriction>
                </simpleType>
            </element>
            <element name = "deliveryTime" type = "date"/>
        </sequence>
    </complexType>
        
    
            <simpleType name = "restrictedEnergyType">
                <restriction base = "positiveInteger">
                    <minInclusive value = "300"/>
                    <maxInclusive value = "500"/>
                </restriction>
            </simpleType>

            <complexType name = "Energy">
                <simpleContent>
                    <extension base = "tns:restrictedEnergyType">
                        <attribute name = "unit" type = "string" use = "optional"/>
                    </extension>
                </simpleContent>
            </complexType>   

            <simpleType name="Type">
                <restriction base = "string">
                    <enumeration value = "caramel"/>
                    <enumeration value = "chocolateNuts"/>
                    <enumeration value = "chocolateSouffle"/>
                </restriction>
            </simpleType>

    <complexType name="Ingridients">
        <sequence>
            <element name = "water" type = "tns:Water"/>
            <element name = "sugar" type = "tns:Sugar"/> 
            <element name = "fructose" type = "tns:Fructose"/>
            <element name = "vanilin" type = "tns:Vanilin"/>          
        </sequence>
        <attribute name = "chocotype" type = "string" use = "optional"/>
    </complexType>
    
            <simpleType name = "restrictedWaterType">
                <restriction base = "positiveInteger">
                    <maxInclusive value = "300"/>
                </restriction>
            </simpleType>

            <complexType name = "Water">
                <simpleContent>
                    <extension base = "tns:restrictedWaterType">
                        <attribute name = "unit" type = "string" use = "optional"/>
                    </extension>
                </simpleContent>
            </complexType>      

            <simpleType name = "restrictedSugarType">
                <restriction base = "positiveInteger">
                    <maxInclusive value = "500"/>
                </restriction>
            </simpleType>

            <complexType name = "Sugar">
                <simpleContent>
                    <extension base = "tns:restrictedSugarType">
                        <attribute name = "unit" type = "string" use = "required"/>
                    </extension>
                </simpleContent>
            </complexType>   

            <simpleType name = "restrictedFructoseType">
                <restriction base = "positiveInteger">
                    <maxInclusive value = "300"/>
                </restriction>
            </simpleType>

            <complexType name = "Fructose">
                <simpleContent>
                    <extension base = "tns:restrictedFructoseType">
                        <attribute name = "unit" type = "string" use = "required"/>
                    </extension>
                </simpleContent>
            </complexType>        

                <simpleType name = "restrictedVanilinType">
                <restriction base = "positiveInteger">
                    <maxInclusive value = "100"/>
                </restriction>
            </simpleType>

            <complexType name = "Vanilin">
                <simpleContent>
                    <extension base = "tns:restrictedVanilinType">
                        <attribute name = "unit" type = "string" use = "required"/>
                    </extension>
                </simpleContent>
            </complexType>    

    <complexType name="Value">
        <sequence>
            <element name = "protein" type = "tns:Protein"/>            
            <element name = "fat" type = "tns:Fat"/>           
            <element name = "carbohydrate" type = "tns:Carbohydrate"/> 
        </sequence>
    </complexType> 
    

            <simpleType name = "restrictedProteinType">
                <restriction base = "positiveInteger">
                    <maxInclusive value = "100"/>
                </restriction>
            </simpleType>

            <complexType name = "Protein">
                <simpleContent>
                    <extension base = "tns:restrictedProteinType">
                        <attribute name = "unit" type = "string" use = "required"/>
                    </extension>
                </simpleContent>
            </complexType>    

            <simpleType name = "restrictedFatType">
                <restriction base = "positiveInteger">
                    <maxInclusive value = "100"/>
                </restriction>
            </simpleType>

            <complexType name = "Fat">
                <simpleContent>
                    <extension base = "tns:restrictedFatType">
                        <attribute name = "unit" type = "string" use = "required"/>
                    </extension>
                </simpleContent>
            </complexType>    
        
            <simpleType name = "restrictedCarbohydrateType">
                <restriction base = "positiveInteger">
                    <maxInclusive value = "100"/>
                </restriction>
            </simpleType>

            <complexType name = "Carbohydrate">
                <simpleContent>
                    <extension base = "tns:restrictedCarbohydrateType">
                        <attribute name = "unit" type = "string" use = "required"/>
                    </extension>
                </simpleContent>
            </complexType>            
        
</schema>

=== ilialeonov/Epam_training/task4/Candies/Candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.epam.by/candies"
        xsi:schemaLocation="http://www.epam.by/candies candies.xsd">
    <candy>
        <name> Raffaello </name>
        <energy>412</energy>
        <type>chocolateSouffle</type>
        <ingridients chocotype="white">
            <water>206</water>
            <sugar>416</sugar>
            <fructose>210</fructose>
            <vanilin>56</vanilin>
        </ingridients>
        <value>
            <protein>52</protein>
            <fat>12</fat>
            <carbohydrate>36</carbohydrate>
        </value>
        <production>Raffaello</production>
        <deliveryTime>2017-09-24</deliveryTime>
    </candy>

    <candy>
        <name>Alonka</name>
        <energy>484</energy>
        <type>chocolateNuts</type>
        <ingridients chocotype="milk">
            <water>110</water>
            <sugar>380</sugar>
            <fructose>180</fructose>
            <vanilin>70</vanilin>
        </ingridients>
        <value>
            <protein>50</protein>
            <fat>10</fat>
            <carbohydrate>40</carbohydrate>
        </value>
        <production>Communarka</production>
        <deliveryTime>2017-06-04</deliveryTime>
    </candy>
    
    <candy>
        <name>Sorvanec</name>
        <energy>435</energy>
        <type>chocolateNuts</type>
        <ingridients chocotype="milk">
            <water>88</water>
            <sugar>366</sugar>
            <fructose>142</fructose>
            <vanilin>86</vanilin>
        </ingridients>
        <value>
            <protein>44</protein>
            <fat>16</fat>
            <carbohydrate>40</carbohydrate>
        </value>
        <production>Communarka</production>
        <deliveryTime>2017-05-11</deliveryTime>
    </candy>
    
    <candy>
        <name>MonCheri</name>
        <energy>307</energy>
        <type>chocolateSouffle</type>
        <ingridients chocotype="milk">
            <water>216</water>
            <sugar>330</sugar>
            <fructose>70</fructose>
            <vanilin>99</vanilin>
        </ingridients>
        <value>
            <protein>40</protein>
            <fat>19</fat>
            <carbohydrate>41</carbohydrate>
        </value>
        <production>Ferrero</production>
        <deliveryTime>2017-07-21</deliveryTime>
    </candy>
    
    <candy>
        <name>Belochka</name>
        <energy>354</energy>
        <type>chocolateNuts</type>
        <ingridients chocotype="milk">
            <water>88</water>
            <sugar>330</sugar>
            <fructose>180</fructose>
            <vanilin>96</vanilin>
        </ingridients>
        <value>
            <protein>54</protein>
            <fat>24</fat>
            <carbohydrate>22</carbohydrate>
        </value>
        <production>Communarka</production>
        <deliveryTime>2017-01-09</deliveryTime>
    </candy>
    
    <candy>
        <name>Yummi</name>
        <energy>322</energy>
        <type>caramel</type>
        <ingridients>
            <water>30</water>
            <sugar>333</sugar>
            <fructose>66</fructose>
            <vanilin>6</vanilin>
        </ingridients>
        <value>
            <protein>41</protein>
            <fat>44</fat>
            <carbohydrate>12</carbohydrate>
        </value>
        <production>Roshen</production>
        <deliveryTime>2017-03-14</deliveryTime>
    </candy>
    
    <candy>
        <name>Nuts</name>
        <energy>432</energy>
        <type>chocolateNuts</type>
        <ingridients chocotype="bitter">
            <water>103</water>
            <sugar>404</sugar>
            <fructose>106</fructose>
            <vanilin>44</vanilin>
        </ingridients>
        <value>
            <protein>51</protein>
            <fat>14</fat>
            <carbohydrate>35</carbohydrate>
        </value>
        <production>Nestle</production>
        <deliveryTime>2017-05-06</deliveryTime>
    </candy>
    
    <candy>
        <name>Michelle</name>
        <energy>336</energy>
        <type>caramel</type>
        <ingridients>
            <water>12</water>
            <sugar>336</sugar>
            <fructose>77</fructose>
            <vanilin>18</vanilin>
        </ingridients>
        <value>
            <protein>12</protein>
            <fat>66</fat>
            <carbohydrate>22</carbohydrate>
        </value>
        <production>Rossia</production>
        <deliveryTime>2017-03-01</deliveryTime>
    </candy>
    
    <candy>
        <name>Gnom</name>
        <energy>312</energy>
        <type>chocolateSouffle</type>
        <ingridients chocotype="ruby">
            <water>200</water>
            <sugar>400</sugar>
            <fructose>15</fructose>
            <vanilin>44</vanilin>
        </ingridients>
        <value>
            <protein>16</protein>
            <fat>72</fat>
            <carbohydrate>12</carbohydrate>
        </value>
        <production>Spartak</production>
        <deliveryTime>2017-04-08</deliveryTime>
    </candy>
    
    <candy>
        <name>Champagne</name>
        <energy>305</energy>
        <type>chocolateSouffle</type>
        <ingridients chocotype="ruby">
            <water>44</water>
            <sugar>404</sugar>
            <fructose>34</fructose>
            <vanilin>12</vanilin>
        </ingridients>
        <value>
            <protein>33</protein>
            <fat>33</fat>
            <carbohydrate>34</carbohydrate>
        </value>
        <production>Chocmod</production>
        <deliveryTime>2017-05-02</deliveryTime>
    </candy>
    
    <candy>
        <name>Marshmellow</name>
        <energy>301</energy>
        <type>chocolateSouffle</type>
        <ingridients chocotype="bitter">
            <water>88</water>
            <sugar>356</sugar>
            <fructose>22</fructose>
            <vanilin>34</vanilin>
        </ingridients>
        <value>
            <protein>12</protein>
            <fat>77</fat>
            <carbohydrate>11</carbohydrate>
        </value>
        <production>Chocmod</production>
        <deliveryTime>2017-03-22</deliveryTime>
    </candy>
   
    <candy>
        <name>Snickers</name>
        <energy>466</energy>
        <type>chocolateNuts</type>
        <ingridients chocotype="milk">
            <water>66</water>
            <sugar>444</sugar>
            <fructose>11</fructose>
            <vanilin>23</vanilin>
        </ingridients>
        <value>
            <protein>56</protein>
            <fat>22</fat>
            <carbohydrate>22</carbohydrate>
        </value>
        <production>Nestle</production>
        <deliveryTime>2017-04-17</deliveryTime>
    </candy>

   
    <candy>
        <name>Bounty</name>
        <energy>377</energy>
        <type>chocolateSouffle</type>
        <ingridients chocotype="milk">
            <water>42</water>
            <sugar>356</sugar>
            <fructose>48</fructose>
            <vanilin>52</vanilin>
        </ingridients>
        <value>
            <protein>30</protein>
            <fat>22</fat>
            <carbohydrate>48</carbohydrate>
        </value>
        <production>Nestle</production>
        <deliveryTime>2017-11-02</deliveryTime>
    </candy>
    
   
    <candy>
        <name>Twix</name>
        <energy>402</energy>
        <type>chocolateNuts</type>
        <ingridients chocotype="milk">
            <water>41</water>
            <sugar>356</sugar>
            <fructose>18</fructose>
            <vanilin>11</vanilin>
        </ingridients>
        <value>
            <protein>41</protein>
            <fat>27</fat>
            <carbohydrate>32</carbohydrate>
        </value>
        <production>Nestle</production>
        <deliveryTime>2017-11-12</deliveryTime>
    </candy>

   
    <candy>
        <name>Nesquick</name>
        <energy>320</energy>
        <type>chocolateSouffle</type>
        <ingridients chocotype="milk">
            <water>88</water>
            <sugar>300</sugar>
            <fructose>22</fructose>
            <vanilin>45</vanilin>
        </ingridients>
        <value>
            <protein>46</protein>
            <fat>23</fat>
            <carbohydrate>31</carbohydrate>
        </value>
        <production>Nestle</production>
        <deliveryTime>2017-08-12</deliveryTime>
    </candy>      
    
    <candy>
        <name>Bombom</name>
        <energy>308</energy>
        <type>chocolateSouffle</type>
        <ingridients>
            <water>6</water>
            <sugar>322</sugar>
            <fructose>88</fructose>
            <vanilin>16</vanilin>
        </ingridients>
        <value>
            <protein>12</protein>
            <fat>66</fat>
            <carbohydrate>22</carbohydrate>
        </value>
        <production>SweetCountry</production>
        <deliveryTime>2017-04-11</deliveryTime>
    </candy>                                                                                                                                                                                                                                                         
</candies>

=== ilialeonov/Epam_training/task4/Candies/dataXML/Candies_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.epam.by/candies"
        xsi:schemaLocation="http://www.epam.by/candies candies.xsd">
    <candy>
        <name>Raffaello</name>
        <energy unit = "kkal">412</energy>
        <type>chocolateSouffle</type>
        <ingridients chocotype="white">
            <water unit = "ml">206</water>
            <sugar unit = "mg">416</sugar>
            <fructose unit = "mg">210</fructose>
            <vanilin unit = "mg">56</vanilin>
        </ingridients>
        <value>
            <protein unit = "g">52</protein>
            <fat unit = "g">12</fat>
            <carbohydrate unit = "g">36</carbohydrate>
        </value>
        <production>Raffaello</production>
        <deliveryTime>2017-09-24</deliveryTime>
    </candy>
</candies>
